### ISSUE TITLE
Redundant Restart button

### ISSUE THREAD

**Issue by marthendalnunes** [commons-stack/c-sim-front-end#103]
When designing the commons, we have the button `Exit`, on the top right corner, which takes the user back to the beginning of the game (watching again the intro, inserting the name, etc). The `Restart` button, on the top left corner, takes the user back to the selection of a number of hatchers, but it can be done just by clicking on the hatchers box on the left.

![image](https://user-images.githubusercontent.com/18421017/104125154-c47e9680-5333-11eb-8ce8-dd702e44f319.png)

**Comment by mendesfabio** [comment]
Restart button was replaced with a Levels button to fix #54.
