### ISSUE TITLE
Intro 7 - graphic revision so text is legible & add pause

### ISSUE THREAD

**Issue by Danibelle** [commons-stack/c-sim-front-end#11]
I love the effect of the text bar across the circle but it’s hard to read the text of someone and planet.
It would be great to make the “But When?” come in after save the planet…. 
[Pause]
But to When?

TEXT CHANGE: They can now send someone back to a pivotal point in the past…
...but to when?

![image](https://user-images.githubusercontent.com/39466970/100807412-e2351380-33f7-11eb-8487-b184c85e3aac.png)

**Comment by markoprljic** [comment]
Options for new images. @Danibelle 

<img width="641" alt="Image 2020-12-19 at 2 52 02 pm" src="https://user-images.githubusercontent.com/5704285/102691033-d88a1900-4209-11eb-92de-0f35c6238317.png">


<img width="676" alt="Image 2020-12-19 at 2 50 09 pm" src="https://user-images.githubusercontent.com/5704285/102691030-d32cce80-4209-11eb-9c27-6945cf7da219.png">

**Comment by mendesfabio** [comment]
Hey, @Danibelle! What do you think about those pictures?

**Comment by Danibelle** [comment]
Let's go with the wistful spaceman gazing into the light.. !!

**Comment by markoprljic** [comment]
@mendesfabio Final image selection for this screen https://user-images.githubusercontent.com/5704285/102691030-d32cce80-4209-11eb-9c27-6945cf7da219.png
