### ISSUE TITLE
Mobile Version: Name Autofill suggestion is linked to Google Pay

### ISSUE THREAD

**Issue by laurenluz** [commons-stack/c-sim-front-end#114]
When I enter my name in Chrome on the mobile version, the autofill suggestion popup includes Google Pay with my credit card info. This doesn't normally happen when I'm filling out just my name on non-payment forms...

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/af5197bd-b5b8-413e-9378-9174d126eb3c)

**Comment by GriffGreen** [comment]
Android thinks the input field is for payment info... we need to tell android this field accepts text only

**Comment by MerlinEgalite** [comment]
Seems that's already to text only by default...

**Comment by laurenluz** [comment]
I just checked/tested again. Seems like it's still popping up with AutoPay fill.

**Comment by mendesfabio** [comment]
It shouldn't be happening since the input has text type. I also asked friends to test it on different Android versions, but they didn't face that pop-up. Maybe it's a bug related to the Android version or the browser used.
