### ISSUE TITLE
Intro 8 - Text Edit & NEW Picture!

### ISSUE THREAD

**Issue by Danibelle** [commons-stack/c-sim-front-end#12]
TEXT CHANGE: 

With cadCAD in hand, new incentivized economic systems can be created that appropriately value the precious resources of our planet. 

![image](https://user-images.githubusercontent.com/39466970/100808016-ff1e1680-33f8-11eb-961d-d1305cc220f8.png)

**Comment by Danibelle** [comment]
Need to find a more optimystic photo for this one..

**Comment by markoprljic** [comment]
Photo suggestion. 
![Uploading Image 2020-12-19 at 12.44.21 pm.png…]()
