### ISSUE TITLE
Add more interesting information to the front end?

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/c-sim-front-end#122]
- [x] Prepare a google sheet of options 
- [x] Send sheet to Marko
- [x] Marko will look at it and think about it
- [x] Vitor, Griff and whoever wants to vote on parameters from the sheet that they think are most relevant to the user (group them)
- [x] Marko will mockup the summary/results page with additional information/data

**Comment by marthendalnunes** [comment]
https://docs.google.com/spreadsheets/d/1X0w3MWh7qraloqIZtg0wyc0La_T0RHnjpE3jPQM6Ygg/edit?usp=sharing

**Comment by santteegt** [comment]
Related to #26

**Comment by GriffGreen** [comment]
Marko to finish!

**Comment by markoprljic** [comment]
Proposal :)

<img width="1012" alt="Image 2021-02-09 at 2 07 47 pm" src="https://user-images.githubusercontent.com/5704285/107367952-3a675080-6ae0-11eb-9bcb-373e1a675f4f.png">

**Comment by mendesfabio** [comment]
May I add it to the FE, @markoprljic?

**Comment by markoprljic** [comment]
> May I add it to the FE, @markoprljic?

Yes.
