### ISSUE TITLE
Intro 11 - Text editing for pauses

### ISSUE THREAD

**Issue by Danibelle** [commons-stack/c-sim-front-end#13]
Again here, make the text show up more like a comic book, fading the sentence in short phrases appearing on the image..
TEXT CHANGES: 
When and where will you land?
[pause]
What social impact movement has the greatest chance of
[pause]
Creating a self-governing, regenerative Commons?

![image](https://user-images.githubusercontent.com/39466970/100808887-a0f23300-33fa-11eb-85df-e6912e7165a7.png)

**Comment by Danibelle** [comment]
Better thank you! And.. the spacing doesn't look so good.. please take out the blank lines between!

When and where will you land? [pause]
What social impact movement has the best chance [pause]
of creating a self-governing, regenerative Commons?

Question, Is it possible to set the time between slides differently or are they all the same?

**Comment by GriffGreen** [comment]
Will be solved by #10
