### ISSUE TITLE
Add tool tips to so that user can click for more info

### ISSUE THREAD

**Issue by laurenluz** [commons-stack/c-sim-front-end#137]
Going through the simulator with @Danibelle and noticing some issues...

Suggesting to add a hovering hand/tool tips so when the user mouses over key words, they can click to open the "Help" popup.

For example, when mousing over "Funding Pool" or "RxC Reserve" on the hatch tribute page (image 1), could have the hovering hand and a popup that says "click for more info" leading to our "Help" popup (image 2)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/f744c4ba-65b9-4453-b36e-e83e84cc9494) 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/144a1929-2533-42da-a945-441434d2a999)

**Comment by laurenluz** [comment]
would love your feedback @markoprljic ... maybe this is a nice-to-have

**Comment by markoprljic** [comment]
@laurenluz This is a good idea. We already planned tooltips in design for certain areas in UI. I wouldn't make them that generic but instead, provide an explanation of what the element on the screen stands for + link to Help for more info.

We can make a list of all tooltips for each level including the text (must be really short). Would you be up to do the list for that?

**Comment by MerlinEgalite** [comment]
Hey! Will you put here the locations and designs for tooltips?

**Comment by markoprljic** [comment]
I know where they are in Figma, but they should also be coded and available somewhere. 

<img width="720" alt="Image 2021-02-11 at 4 05 46 pm" src="https://user-images.githubusercontent.com/5704285/107654541-07a98d80-6c83-11eb-89bd-4c69aa08db9b.png">

**Comment by MerlinEgalite** [comment]
Well! can you send the link to figma design please?
And are they ready to be implemented? or some reflections around what to explain and tooltip contents are still need before implementing them on the frontend?

**Comment by markoprljic** [comment]
https://www.figma.com/file/cuFTOOajO4aouz4SLnIINz/Commons-Simulator?node-id=557%3A3297

Anything else? :)

**Comment by laurenluz** [comment]
@MerlinEgalite I'm going to put the tooltips as comments in the figma today and will ping you when they're ready to be implemented on the frontend

**Comment by laurenluz** [comment]
Ok so I added most tooltip content as comments in the figma, here:

https://www.figma.com/file/cuFTOOajO4aouz4SLnIINz/Commons-Simulator?node-id=557%3A3297

Everywhere it says *click for more info* would be great if the user could click that and it would send them to our "more info" popup for that page.

Also, for the results page, I would like to add tooltips on each of the results boxes at the top with content as follows:

- Hatchers: the founding members of the RadicalxChange Commons
- Initial Proposals: the number of project proposals initially collected before the Hatchers begin their voting
- Hatch Tribute: the percentage of total initial funds delegated to the funding pool to fund approved RadicalxChange initiatives
- Max Spending: the maximum percentage of the funds within the Funding Pool that can be withdrawn at any one time
- Voting speed: the amount of time it takes for an individual’s voting power to reach 80% of its full power
- Exit Tribute: the percentage of funds that feeds back into the Funding Pool when members choose to sell their RxC tokens

![image](https://user-images.githubusercontent.com/75490971/107690190-695ffc80-6c6f-11eb-84e1-1e07e8c06fec.png)

(didn't add the last part to the figma because our version now looks really different that what we have in the figma)
