### ISSUE TITLE
Change "Help" to "More Information"

### ISSUE THREAD

**Issue by laurenluz** [commons-stack/c-sim-front-end#138]
The top right corner "Help" button leads to a popup that contains more information for the user. Can we change it from "Help" to "More Info"... I think that would be ultimately more helpful

**Comment by laurenluz** [comment]
@markoprljic what do you think? This is a proposed suggestion from @Danibelle

**Comment by mendesfabio** [comment]
preview of how it would look like to help the discussion:

![image](https://user-images.githubusercontent.com/43360747/107305467-cf773480-6a61-11eb-8d63-043301ee6d5e.png)

**Comment by markoprljic** [comment]
I don't know, I felt Help is what "players" seek in any game when they don't know how to proceed or need some help/instructions.

**Comment by laurenluz** [comment]
just confirmed w @markoprljic that we want to implement this change on the frontend. Please change "Help" to "More Info"

This is also @Danibelle approved
