### ISSUE TITLE
Make waiting for Loading a bit more interesting

### ISSUE THREAD

**Issue by markoprljic** [commons-stack/c-sim-front-end#146]
something like a game of life small simulation or anyway something that gives the idea I am waiting the agents of simulation to work

**Comment by sembrestels** [comment]
Maybe the cadcad logo could spin slowly?

**Comment by markoprljic** [comment]
@sembrestels Yes, rotating the cadCAD logo while loading the simulation, is one small thing to add.

I was also considering rotating some text (sentences) that describe what's happening in the background but also maybe use this waiting time to educate the user more. 

Any suggestions? @marthendalnunes @GriffGreen @laurenluz

**Comment by laurenluz** [comment]
Yeah I love this idea @markoprljic - we can make it educational, gamified and even funny... some ideas for text:

Initializing Hatch
Aggregating proposals
Calibrating Funding Pool
Stabilizing RxC Reserve
Capping relative spending
Implementing conviction voting
Extracting exit tribute 
Averaging token price
Gauging community sentiment
Assessing global impact

@marthendalnunes - what do you think? We can brainstorm even more....

(I loved this in the Sims 2: https://modthesims.info/archive/index.php?t-331011.html)

**Comment by laurenluz** [comment]
Some updated suggestions thanks to @marthendalnunes 

Initializing Hatch
Aggregating starting proposals
Calibrating Funding Pool
Stabilizing RxC Reserve
Capping relative spending
Implementing conviction voting
Generating new participants
Creating new proposals
Calculating proposals’ conviction
Extracting exit tribute
Averaging token price
Gauging community sentiment
Assessing global impact

**Comment by GriffGreen** [comment]
Decide the waiting time average is 1 minute - (30 seconds?)
Decide a number of phrases based on reading time (3-4 seconds)
Decide which phrases to keep

If it's cached, or a fast simulation, fake the loading time ;-) Planned Obsoleteness... FOR THE FUN UX!

**Comment by laurenluz** [comment]
Let's make the load screen last a minimum of 30s, with each of the following phrases lasting 3s:

1. Initializing Hatch...
2. Calibrating Funding Pool...
3. Backing-up RxC Token...
4. Attracting New Participants...
5. Generating New Proposals...
6. Accounting For Speculation...
7. Building Conviction on Proposals...
8. Tallying Project Successes...
9. Gauging Community Sentiment...
10. Assessing Global Impact...

And let's animate the "..." at the end of each phrase. If the simulation takes longer than 30s, the final phrase "Assessing Global Impact..." should just stay with the "..." continuing as an animation.

Right now the load screen looks like this:
![image](https://user-images.githubusercontent.com/75490971/111080302-7157ca00-84c3-11eb-945a-d2e2d014d9e0.png)

I propose we replace "Simulating..." with the above sequence of text, as described. @markoprljic - what do you think? can we get a thumbs up?

**Comment by markoprljic** [comment]
Agree with the suggestion @laurenluz .
@mendesfabio Will you take on this?
