### ISSUE TITLE
Switch results button and graph title on final page

### ISSUE THREAD

**Issue by laurenluz** [commons-stack/c-sim-front-end#151]
I think it will be more intuitive/logical if the graph title is first and larger and then underneath is the clickable link.... like this:

(Bigger) Funding Pool
(Smaller) What do good Funding Pool results look like?

What do you think? @markoprljic 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/93c38705-49e2-4495-95a9-a27066790768)

**Comment by markoprljic** [comment]
Yes, thanks @laurenluz 
Also, make all links green color, on all graphs.

**Comment by mendesfabio** [comment]
I need feedback! Looks good? Maybe change de font, color, or size?

![image](https://user-images.githubusercontent.com/43360747/108842097-85409800-75b7-11eb-80b7-76d9b74146cd.png)

**Comment by markoprljic** [comment]
Great!
