### ISSUE TITLE
Add y-axis titles on results page?

### ISSUE THREAD

**Issue by laurenluz** [commons-stack/c-sim-front-end#152]
What are the units of measurement here for Funding Pool and Token Price?

I think it might add some clarity when the player is analyzing their results if they have more of a feeling of what a token price of "0.5" actually means... even if it's only relatively speaking. Or are we intending for the player just look generally at the shape of the graph? 

@markoprljic @marthendalnunes 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/73e46426-b5e4-444c-b8be-6c91dbca7cc5)

**Comment by markoprljic** [comment]
Yes, those should be added.

**Comment by mendesfabio** [comment]
I need feedback! Looks good? Maybe change de font, color, or size?

![image](https://user-images.githubusercontent.com/43360747/108841010-dfd8f480-75b5-11eb-90b3-c15dcb67bde0.png)

**Comment by GriffGreen** [comment]
xDai for funding pool

xDai/RxC for Price
