### ISSUE TITLE
Make final game score more clear - what does it meaaan? how can the user improve

### ISSUE THREAD

**Issue by laurenluz** [commons-stack/c-sim-front-end#153]
I think it's hard for the user to understand what their score means practically, and how to improve it. I saw this also as feedback in #122

Some suggestions:

- Add information about how the score is calculated
- Add information about penalties, e.g. a penalty of 50 is given if sentiment drops below 0.5
- On final "See your future" page... make "Try to improve your score" a clickable link that leads to a popup with added information

Some suggestions for information to add in "improve score" popup:

- how parameter relate to graphs, e.g. the exit tribute adds funds to the funding pool
- how results relate to each other e.g. a low exit tribute makes speculators more likely... more people selling when token price is high means more increments of funds being added to the funding pool at lower prices

Suggestions might get complex, but perhaps we could compile a list of suggestions and have only one popup at random like a "hint" each time a user clicks open "try to improve your score"... this way we don't need to be totally exhaustive in our list of ways in which a person could design the perfect commons...

Would love some feedback, I think this is important because it affects the user's level of interest. If they can't understand what's going on, they'd lose interest. I think it's our job to provide enough background info that people WANT to dive a little more into the understanding the interconnectedness of the parameters and results, and then get excited about this as a tool.

![image](https://user-images.githubusercontent.com/75490971/108559980-ab1d2280-72c1-11eb-9102-cd008b169fea.png)

**Comment by laurenluz** [comment]
@Danibelle @markoprljic @GriffGreen

**Comment by MerlinEgalite** [comment]
If we make "Try to improve your score" clickable it's the same process play again then? Maybe just have one button is clearer?

I like the idea of random hints. But what if the user get bored and just want to access to all hints?

**Comment by markoprljic** [comment]
It's not about making the text clickable, but adding a bit more information on why this is a bad future and what happened.
If @Danibelle or someone can provide a paragraph of text (both for good and bad future) I'll rework these results screens a bit.

**Comment by GriffGreen** [comment]
It could be related to the metrics explainers that are part this issue: https://github.com/commons-stack/commons-simulator/issues/134

**Comment by GriffGreen** [comment]
Maybe we write a blog post?

**Comment by markoprljic** [comment]
We could put a link below the score and open a page with more explanation on how the score is calculated. This can be a generic text that fits both good and bad outcome.

**Comment by laurenluz** [comment]
Ok here's some suggested text. I think it would be great to have the link say something like "Your Score: What does this mean?" under the score, leading to a popup with the content below:

"Your Score: What Does it Mean?

Your score is a number out of 1000 representing the success of your Commons. A score of 500 or greater indicates that you have selected parameters that, according to cadCAD, will Hatch a Commons that will save the world from ecosystem collapse!

Based on the parameters you selected in each level, cadCAD builds your score using a series of equally weighted metrics. The score, therefore depends on the following:

- Final Token Price compared to Token Price at Hatch
- Final Sentiment
- Number of Funded Proposals compared to number of Initial Proposals
- Total spent by the Funding Pool compared to the amount in the Funding Pool at Hatch
- Average amount in the Funding Pool compared to the amount in the Funding Pool at Hatch
- Average Token Price compared to the Token Price at Hatch
- Average Sentiment
- Ratio of Successful Projects to Failed Projects
- Number of Final Participants compared to the number of Hatchers

You gain points if your Commons grows, gains popularity and positive sentiment, passes and completes value-adding projects, gains stability - you get the idea - and you lose points for the opposite. How did you do?

Share Your Score or Play Again to improve your results!"

And I think it would be really good if we could have the last line "scare your score" or "play again" also be links that direct the user accordingly from within the popup. @markoprljic Do you want to update the design a bit here and pass to Fabio or Merlin?

**Comment by markoprljic** [comment]
Attached modal view for score explanation.
![Image 2021-03-16 at 3 40 16 pm](https://user-images.githubusercontent.com/5704285/111327769-f4b51f00-866d-11eb-97de-a35ab37c3dca.jpg)
