### ISSUE TITLE
Good / Bad future - UI Revisions

### ISSUE THREAD

**Issue by markoprljic** [commons-stack/c-sim-front-end#159]
- Change the font size of titles (Good future bigger, Yoru score smaller)
- Give feedback link / text
- Share results

See attached mockup and updated Figma.

![Image 2021-02-22 at 4.51.03 pm.jpg](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/2e3d1249-e757-4e76-ae27-950e24316f58)

**Comment by MerlinEgalite** [comment]
<img width="1440" alt="Screenshot 2021-02-22 at 21 43 02" src="https://user-images.githubusercontent.com/44097430/108773933-5565a600-755f-11eb-9f6c-c6ab7c7b67e2.png">

Is it better like that?

**Comment by markoprljic** [comment]
Yes
