### ISSUE TITLE
Ref Issue #137: Tool Tips have a duplicate

### ISSUE THREAD

**Issue by Danibelle** [commons-stack/c-sim-front-end#161]
When you click on 'Voting Power' you get the same text popup as the previous one, Funding Pool:

https://commons-stack-game-dev.netlify.app/level/5/1
![image](https://user-images.githubusercontent.com/39466970/108780408-3fcf8c80-751d-11eb-8a0b-40c9c61783d4.png)

**Comment by laurenluz** [comment]
Here's what it should say:

**Conviction Voting: the weight of a person's vote increases over time. *Click for more info***

Also noticed that the tool tip on level 2 initial proposals is missing... on "proposals" it should say:

**Proposals: projects suggested by RadicalxChange members requesting funds. *Click for more info***

![image](https://user-images.githubusercontent.com/75490971/108782562-67c8eb00-7531-11eb-98ef-95b23381e703.png)

@MerlinEgalite
