### ISSUE TITLE
The tool tips should pop up when i scroll over not on a click?

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/c-sim-front-end#166]
<img width="850" alt="Screen Shot 2021-02-23 at 5 33 55 AM" src="https://user-images.githubusercontent.com/14945613/108831902-0f462c00-75cb-11eb-8079-6f1a1ba5df0c.png">

<img width="926" alt="Screen Shot 2021-02-23 at 5 45 54 AM" src="https://user-images.githubusercontent.com/14945613/108833160-b7102980-75cc-11eb-828e-775bcd785806.png">

<img width="388" alt="Screen Shot 2021-02-23 at 5 48 39 AM" src="https://user-images.githubusercontent.com/14945613/108833429-19692a00-75cd-11eb-934c-65384be0a134.png">

<img width="454" alt="Screen Shot 2021-02-23 at 5 51 51 AM" src="https://user-images.githubusercontent.com/14945613/108833818-a4e2bb00-75cd-11eb-925b-55cb74299cbc.png">

**Comment by mendesfabio** [comment]
seems related to #156. could we close in favor of that, @GriffGreen?

**Comment by GriffGreen** [comment]
Yep! Thx @mendesfabio !!! And next time fee free to close when you see a duplicate ;-)
