### ISSUE TITLE
Random graphic on the last page should be behind all the content, not in front of it

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/c-sim-front-end#167]
<img width="526" alt="Screen Shot 2021-02-23 at 6 02 55 AM" src="https://user-images.githubusercontent.com/14945613/108835120-4c142200-75cf-11eb-9210-4ef8be37e23b.png">
<img width="528" alt="Screen Shot 2021-02-23 at 6 02 46 AM" src="https://user-images.githubusercontent.com/14945613/108835125-4ddde580-75cf-11eb-8613-992571b35d1d.png">

**Comment by MerlinEgalite** [comment]
Hmm I see it behind buttons, result's graphs, etc. 🤨
I'm not sure... what rendering you want?

**Comment by GriffGreen** [comment]
Remove that thing from the results
