### ISSUE TITLE
The "Telegram or discord handle" text doesnt resize well

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/c-sim-front-end#175]
(NOT A BLOCKER FOR LAUNCH) @markoprljic how should it respond? should we make this text shorter?

<img width="926" alt="Screen Shot 2021-02-24 at 7 15 32 AM" src="https://user-images.githubusercontent.com/14945613/108999318-6b2fb400-76a2-11eb-9cc9-8f0bec07420c.png">
<img width="597" alt="Screen Shot 2021-02-24 at 7 15 17 AM" src="https://user-images.githubusercontent.com/14945613/108999331-6d920e00-76a2-11eb-953d-c41e883c148d.png">
<img width="250" alt="Screen Shot 2021-02-24 at 7 15 07 AM" src="https://user-images.githubusercontent.com/14945613/108999332-6e2aa480-76a2-11eb-8135-2d9b0780cbd9.png">

**Comment by markoprljic** [comment]
Where did that come from!? :D

Ok, I think we should do it like this...

![Image 2021-02-24 at 1 55 59 pm](https://user-images.githubusercontent.com/5704285/109003689-0d05cf80-76a8-11eb-914c-b1c7db6ac23c.jpg)
