### ISSUE TITLE
Make POAPS.... need an image then Griff can deploy

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/c-sim-front-end#183]
![Screen Shot 2021-03-02 at 7.54.53 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/8d0407b3-33c1-4d21-b644-eaf372ea590a)

**Comment by markoprljic** [comment]
@GriffGreen Check this. 
![POAP Commons Simulator](https://user-images.githubusercontent.com/5704285/109696913-dd663400-7b8d-11eb-9c28-16628ea8ea95.png)

**Comment by GriffGreen** [comment]
Oh yeah i fucking love it

**Comment by markoprljic** [comment]
I'm a pizza bagel...
