### ISSUE TITLE
Tighten up screen sizing to reduce scrolling on single pages

### ISSUE THREAD

**Issue by Danibelle** [commons-stack/c-sim-front-end#189]
I have tested this on multiple sized laptop screens and frequently have to scroll just a little to get to the NEXT button.

Pretty sure we can tweak this to make the page size appropriately whether I'm on a 13, 15, 17 inch laptop or giant monitor, for example.

![image](https://user-images.githubusercontent.com/39466970/109683506-06aea200-7b45-11eb-86d6-ade7a77d8df8.png)

![image](https://user-images.githubusercontent.com/39466970/109683544-10d0a080-7b45-11eb-871e-fff910f54a57.png)

![image](https://user-images.githubusercontent.com/39466970/109683612-21811680-7b45-11eb-848d-a33f63b44996.png)

![image](https://user-images.githubusercontent.com/39466970/109683631-28a82480-7b45-11eb-8a4d-77dd9db08415.png)

![image](https://user-images.githubusercontent.com/39466970/109683663-31005f80-7b45-11eb-968c-02e05361948a.png)

![image](https://user-images.githubusercontent.com/39466970/109683692-378ed700-7b45-11eb-81f5-0c867102f248.png)

![image](https://user-images.githubusercontent.com/39466970/109683743-41b0d580-7b45-11eb-81b5-c97c53c20d20.png)
![image](https://user-images.githubusercontent.com/39466970/109683788-49707a00-7b45-11eb-8875-89bc6c8c24c0.png)

**Comment by MerlinEgalite** [comment]
Do you want I do the same for text explanation @Danibelle? I mean the explanation screen (not when users set parameters). In case yes, can we reduce a little bit the text size?

**Comment by Danibelle** [comment]
I think the text size has room for reduction, yes!
