### ISSUE TITLE
Firefox doesn't work so great - Intro Images disapear after a moment.

### ISSUE THREAD

**Issue by LinuxIsCool** [commons-stack/c-sim-front-end#19]
As I'm going through the intro right now,the background images disappear to a grey background after about one second.

**Comment by LinuxIsCool** [comment]
This is happening on  Firefox on Linux - popos 20.10.

**Comment by GriffGreen** [comment]
Going to be addressed with some of Dani's Release

**Comment by MerlinEgalite** [comment]
I guess this issue can be closed as there is not anymore this issue (at least on my computer Mac OS) but maybe I'm misleading
