### ISSUE TITLE
Replace "Good Future" "Bad Future" text with cool messaging

### ISSUE THREAD

**Issue by Danibelle** [commons-stack/c-sim-front-end#191]
What shall we replace it with..  let's brainstorm in the Telegram chat!

Can we make it a random set of congratulation messages and oh no messages?

![image](https://user-images.githubusercontent.com/39466970/109816344-7a07f080-7be5-11eb-9740-8e729f7b2f04.png)

![won internet](https://user-images.githubusercontent.com/39466970/109816399-8be99380-7be5-11eb-845a-f5f8a76d9501.gif)

**Comment by MerlinEgalite** [comment]
Yes! 
Do you want to add GIFs too? 😆

**Comment by markoprljic** [comment]
Well done, your future looks good!
Oh no, your future is bad.

**Comment by mendesfabio** [comment]
I've already implemented the feature on the front-end to randomly pick up one of the good/bad future phrases. Now, we just need to brainstorm 😄 I'm leaving some suggestions:

```
      bad: [
        'Oh no! Your future is bad.',
        'You failed to save the future.',
        'GAME OVER! Your future looks bad.',
        'Oops! You designed badly your Commons.'
      ],
      good: [
        'Well done, your future looks good!', 
        'WOO-HOO! You saved the planet.', 
        'You nailed it! Congratulations.',
        'Yay! You accomplished your mission.'
      ],
```

**Comment by markoprljic** [comment]
Looks good to me! :)

**Comment by Danibelle** [comment]
Bad Future
0-124 - Your future is so bad you must have tried to fail! 🤯 
125-249 - Oh no! Life on earth will not survive with these conditions, try again! 💀 
250-374 - You clearly need help. Try again, with very different choices! 😬 
375-499 - Not quite! You are so close to saving the planet, please play again. 😕 

Good Future
500-624 - Oh Yeah! You've saved the planet, play again to improve your score! 🤠 
625-749 - You made great choices! The future looks bright for your Commons. 😎 
750-874 - Congratulations, you nailed it! Humanity is saved thanks to you! 🤗 
875-1000 - Amazing, you win! You've clearly been doing your homework! 🥳

**Comment by markoprljic** [comment]
I would just leave out emojis for design style consistency with the rest of the app.

**Comment by Danibelle** [comment]
yeah, I know.. but it was fun to think about the vibe for each one and show it.. 😉
