### ISSUE TITLE
the text sometimes becomes hard to read in the intro

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/c-sim-front-end#2]
<img width="400" alt="Screen Shot 2020-12-01 at 11 31 22 AM" src="https://user-images.githubusercontent.com/14945613/100768349-15c56d00-33fb-11eb-97ce-7aed1ad26492.png">

**Comment by markoprljic** [comment]
Related https://github.com/commons-stack/c-sim-front-end/issues/11
@GriffGreen Close please
