### ISSUE TITLE
Add enclosed line of text to narrative as shown

### ISSUE THREAD

**Issue by Danibelle** [commons-stack/c-sim-front-end#23]
Where it says this (as shown in Image below): Who am I?
Looking at the phone in your pocket you intuitively know how to unlock it and scroll through to find out that your name is Nik.

Add this sentence: When your calendar shows you are on your way to host a RadicalxChange meeting at the Akasha Hub in Barcelona, your excitement builds!

![image](https://user-images.githubusercontent.com/39466970/101515386-ea370b00-3943-11eb-934b-f450a5797d3e.png)

**Comment by Danibelle** [comment]
Awaiting the #35 to verify..  unless there is a staging area I can check to see changes before that?

**Comment by mendesfabio** [comment]
> Awaiting the #35 to verify.. unless there is a staging area I can check to see changes before that?

Now, it's live on https://sim.commonsstack.org/. I'll close this issue, but if you have any suggestions, open a new one!
