### ISSUE TITLE
Results screen - update graphs with the ones we use on other Levels

### ISSUE THREAD

**Issue by markoprljic** [commons-stack/c-sim-front-end#24]
On the results page, can we use the same graphs UI that we use on the Levels? 

<img width="888" alt="Image 2020-12-08 at 5 54 53 pm" src="https://user-images.githubusercontent.com/5704285/101515429-a1507800-397e-11eb-8874-564f7c4a139b.png">

<img width="686" alt="Image 2020-12-08 at 5 56 23 pm" src="https://user-images.githubusercontent.com/5704285/101515507-b62d0b80-397e-11eb-9f27-71d52a49832c.png">

**Comment by mendesfabio** [comment]
can we close it, right @MerlinEgalite?
