### ISSUE TITLE
Add Tooltip to graphs and sliders

### ISSUE THREAD

**Issue by markoprljic** [commons-stack/c-sim-front-end#25]
Add a tooltip to the graph and sliders (or elsewhere) with information explaining what the generated curve means. 

<img width="367" alt="Image 2020-12-08 at 5 58 40 pm" src="https://user-images.githubusercontent.com/5704285/101515792-099f5980-397f-11eb-8c24-5ef7f2b197b4.png">
<img width="565" alt="Image 2020-12-08 at 5 58 47 pm" src="https://user-images.githubusercontent.com/5704285/101515795-0ad08680-397f-11eb-8079-71d169cfe81b.png">

**Comment by GriffGreen** [comment]
DONE!
