### ISSUE TITLE
LEVEL 2 - The max amout of initial proposals is not clear

### ISSUE THREAD

**Issue by marthendalnunes** [commons-stack/c-sim-front-end#27]
![image](https://user-images.githubusercontent.com/18421017/101516007-b9fc6600-395d-11eb-99f1-126e8fd92257.png)

**Comment by GriffGreen** [comment]
If you look at the Hatchers there is a min and a max.... here there is no understanding what the min and max

Just as a slider and have the number show up on top of it.
