### ISSUE TITLE
Reformat images to progressive when possible

### ISSUE THREAD

**Issue by sembrestels** [commons-stack/c-sim-front-end#29]
That may offer a better user experience in low speed connections.

https://www.liquidweb.com/kb/what-is-a-progressive-jpeg/

**Comment by GriffGreen** [comment]
put the images in gimp and configure the images so they appear better where there is a good connection

**Comment by markoprljic** [comment]
We must start preloading intro images as soon as user opens the site. When user starts the intro the images should already be loaded or at least the first few, progressively load other.

**Comment by GriffGreen** [comment]
Some updates in telegram for options... but nothing great... @MerlinEgalite is looking for tools
