### ISSUE TITLE
LEVEL 2 - Add decrement/increment buttons

### ISSUE THREAD

**Issue by mendesfabio** [commons-stack/c-sim-front-end#30]
I think that we could add buttons (+/-). Also, when the user access Level 2, its cursor should be placed into the field.

<img width="1023" alt="Screen Shot 2020-12-08 at 14 00 58" src="https://user-images.githubusercontent.com/43360747/101516205-f334d600-395d-11eb-88d9-c70cde71f0da.png">

**Comment by GriffGreen** [comment]
Low pri

**Comment by mendesfabio** [comment]
#27 will solve it with a range slider.
