### ISSUE TITLE
Create a text explanation for what is Token Price

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/c-sim-front-end#38]

**Comment by laurenluz** [comment]
Token Price: the monetary value associated with the purchase of a token. RxC tokens are backed by the RxC reserve, ensuring that they always have monetary value. Token price, however, can fluctuate – decreasing if members sell their tokens (withdrawing value from the community), and increasing as members contribute time and resources (growing the commons and adding value to the community).
