### ISSUE TITLE
Create a Graphical explanation for what is a good Funding Pool chart

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/c-sim-front-end#41]

**Comment by markoprljic** [comment]
@GriffGreen Please provide more context.

**Comment by santteegt** [comment]
Related to #26

**Comment by santteegt** [comment]
@mendesfabio @MerlinEgalite how do you plan to show this graph? Image vs fetching data and plotting it using the same charting library being used to show the results?

**Comment by mendesfabio** [comment]
@santteegt I would plot using the same charting library. I just don't know if you need to serve this data on the backend. What do you think about it, @MerlinEgalite?
