### ISSUE TITLE
Find a good future picture

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/c-sim-front-end#44]

**Comment by markoprljic** [comment]
Options...

<img width="671" alt="Image 2020-12-19 at 12 37 50 pm" src="https://user-images.githubusercontent.com/5704285/102688481-37926280-41f7-11eb-8b05-5833fa6364f8.png">

![Uploading Image 2020-12-19 at 12.30.05 pm.png…]()

**Comment by GriffGreen** [comment]
Can we find a more solar punk future?

**Comment by GriffGreen** [comment]
super happy burning man solar punk green healthy vibrant cyberpunk

**Comment by laurenluz** [comment]
This is a cool one: https://jessicaperlstein.com/collections/artwork/products/the-fifth-sacred-thing-1
Also this: https://jessicaperlstein.com/collections/artwork/products/reclaim-1

Danibelle knows the artist and so we sent an email out to ask for permission to use. Will update once we hear back.

**Comment by markoprljic** [comment]
Funny story, I found the exact same image from Jessica but couldn't use it
because of copyright.

If we can get it then fine BUT bad future should be same style, like
illustrations.

Maybe better to go with a photo.
