### ISSUE TITLE
Implement multiple bad futures and maybe good futures (Formerly find a bad future picture)

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/c-sim-front-end#45]
Changing this issue as the current bad future is fine, but it would be cool if we had different levels of bad.... like 300-400 you get a sort of bad future.. maybe the gas mask guy... 200- 300 you get the doll, 100-200 the world is destroyed ;-D

We might also have levels of good futures?

**Comment by markoprljic** [comment]
Options...

<img width="885" alt="Image 2020-12-19 at 12 26 58 pm" src="https://user-images.githubusercontent.com/5704285/102688461-1a5d9400-41f7-11eb-9fda-1cba85424819.png">

![Uploading Image 2020-12-19 at 12.24.25 pm.png…]()

**Comment by markoprljic** [comment]
@Danibelle Uploading new samples for Bad future.
![Bad Future](https://user-images.githubusercontent.com/5704285/102912280-7a656c00-447d-11eb-8c80-83b2bb0f1ba4.png)
![Bad Future-1](https://user-images.githubusercontent.com/5704285/102912298-7e918980-447d-11eb-8636-696d90a79121.png)
![Bad Future-2](https://user-images.githubusercontent.com/5704285/102912312-818c7a00-447d-11eb-8071-d55d5fe4fac0.png)
![Bad Future-3](https://user-images.githubusercontent.com/5704285/102912321-85200100-447d-11eb-8da9-939b9a0124a3.png)

**Comment by laurenluz** [comment]
Something like these burning earths might be cool:

https://www.shutterstock.com/image-illustration/burning-world-earth-3d-rendering-1511497112
https://www.shutterstock.com/image-illustration/view-planet-earth-burning-space-3d-577252162

Or the apocalytic city:

I can make an account w a free trial if we like this and get access.

**Comment by markoprljic** [comment]
Thanks @laurenluz 
Not sure about burning earth as well as the very detailed apocalyptic scene. When looking for images I try to find ones that have a close-up scene that is visible on the left and right side (because content is in the middle).

Did you check the above examples I posted? 

cc/ @GriffGreen @Danibelle

**Comment by Danibelle** [comment]
These still seem too optimistic, humanity still dresses nice and has cool
things..

Bad future is described as life is destroyed.. game over..

danibelle

**Comment by Danibelle** [comment]
These still seem too optimistic, humanity still dresses nice and has cool things..


Bad future is described as life is destroyed.. game over..

**Comment by laurenluz** [comment]
What do you kids think about using this art by Mark Henson... focusing on the bad half for the bad future and the good half for the good future?

I emailed him last week for permission and he said he's willing as long as he is credited (name, title of art and link to site if appropriate), and he was asking questions about whether there will be a profit. He's happy to share his pictures for free for non-profit endeavors but if there's a profit he wants a little piece...

https://www.markhensonart.com/mark-s-home-warehouse/original_art_products/new-pioneers

**Comment by markoprljic** [comment]
Oh wow! This may fit in well. I'll mock it up and show you.

Thanks!

**Comment by markoprljic** [comment]
@laurenluz See the mockup with Mark's art.

<img width="684" alt="Image 2020-12-30 at 8 18 11 am" sr@GriffGreen ttps://user-images.githubusercontent.com/5704285/103336208-a1bcca00-4a77-11eb-8f4a-ee0e04658101.png">

cc/ @GriffGreen @Danibelle

**Comment by laurenluz** [comment]
Oh I love this! @markoprljic let me know if we're going forward w this so I can show it to Mark and make sure it's ok w him. We also need to credit him, as per his email:

"I would like to see what you want to do with my imagery before I give permission, for which I would want a written agreement.

I would also like to be credited with my name and the title of the artwork, and a link to my site if that is appropriate."

**Comment by markoprljic** [comment]
Please check the Figma file, at the bottom two screens. I added credits.

Please show him those.

**Comment by markoprljic** [comment]
@laurenluz Attached screens to show Mark in regards to the copyright credits. 

![Good Future](https://user-images.githubusercontent.com/5704285/103407955-dc4e6180-4b60-11eb-96f3-d0dca7e992fc.png)

![Bad Future](https://user-images.githubusercontent.com/5704285/103407962-e2444280-4b60-11eb-801e-f452c630fe0d.png)

**Comment by laurenluz** [comment]
Ok I sent them to him earlier today, will let you know when I hear back. Last time it took him about a week to reply... @markoprljic

**Comment by markoprljic** [comment]
Thanks!

**Comment by mendesfabio** [comment]
hey @markoprljic, may I implement this on the frontend?

**Comment by markoprljic** [comment]
> hey @markoprljic, may I implement this on the frontend?

@laurenluz Did we hear back from Mark? Can @mendesfabio implement the images? I assume yes, but double checking.
