### ISSUE TITLE
Rename all the levels

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/c-sim-front-end#5]
<img width="160" alt="Screen Shot 2020-12-01 at 11 43 46 AM" src="https://user-images.githubusercontent.com/14945613/100769784-cf710d80-33fc-11eb-90d0-6b432515b40e.png">

<img width="480" alt="Screen Shot 2020-12-01 at 11 44 30 AM" src="https://user-images.githubusercontent.com/14945613/100769853-e3b50a80-33fc-11eb-9e0a-a92524dcfeae.png">

Intro = Intro

Founding Members = Hatchers

Proposals = Initial Proposals

Funding = Hatch Tribute

Voting Power = Max Spending

Decisions = Voting Speed

Exiting = Exit Tribute

Simulation = Run cadCAD

**Comment by mendesfabio** [comment]
@GriffGreen, should we also change the title of each level page? I mean the browser tabs titles.

**Comment by GriffGreen** [comment]
> @GriffGreen, should we also change the title of each level page? I mean the browser tabs titles.

YES!
