### ISSUE TITLE
Make intro slide PAUSE on TAP

### ISSUE THREAD

**Issue by markoprljic** [commons-stack/c-sim-front-end#58]
When user taps the screen on mobile while watching the Intro screens, make the screen pause for as long as the tap is active.
When user releases the finger from the screen continue with the intro screen animations.

**Comment by mendesfabio** [comment]
Hey, @markoprljic, I've worked on this today. Besides adding the pause on tap feature, I thought it'd be nice to have some progress tracker, like on Instagram stories. What do you think about it?

![image](https://user-images.githubusercontent.com/43360747/108009438-79fed280-6fe1-11eb-8066-3754a559f67a.png)

**Comment by markoprljic** [comment]
YES! Please implement this. Thank you :)
