### ISSUE TITLE
Swap out Image on Designing the Commons

### ISSUE THREAD

**Issue by Danibelle** [commons-stack/c-sim-front-end#65]
Can we use the right half of this image from the Intro, for the image at the left side of this page? The illustration from the previous screen just doesn't make sense here.

![image](https://user-images.githubusercontent.com/39466970/103251030-cc9a0780-492b-11eb-8240-e9890324e978.png)

**Comment by Danibelle** [comment]
Alternately we have this illustration that was drawn for this location - @markoprljic do you have access to this? I see it embedded in the [Narrative Document her](https://docs.google.com/document/d/10eQzJ1XkvN66ltpRXq_vo8rxtDgarX5Q7C8TdJUlGD4/edit#)e..

![Nik cadCAD](https://user-images.githubusercontent.com/39466970/103251143-4cc06d00-492c-11eb-8d42-f6f74c9b1519.png)

**Comment by markoprljic** [comment]
@Danibelle I wouldn't mix illustrations with photos on the intro screens. I'm aware of this one but since we started with photos for intros I'd keep it for consistency. 

Not sure I understood correctly what you meant by the following:

> Can we use the right half of this image from the Intro, for the image at the left side of this page? 

Can you please clarify? Thanks.

**Comment by Danibelle** [comment]
Oh sorry yes this was very unclear!!

I mean for this page (https://sim.commonsstack.org/level/1/1), to replace the illustration repeated here with either of those proposed above:
![image](https://user-images.githubusercontent.com/39466970/103291242-23412900-49a0-11eb-90ba-145b3b681432.png)

**Comment by GriffGreen** [comment]
Oh nice changing up the images a bit does sound like a good idea...

**Comment by markoprljic** [comment]
@Danibelle I'm not sure how to download high-res image from the Narrative doc. Do you happen to have it somewhere and upload it here? Thanks!

**Comment by markoprljic** [comment]
> @Danibelle I'm not sure how to download high-res image from the Narrative doc. Do you happen to have it somewhere and upload it here? Thanks!

I took the screenshot from the doc for the mockup. See below. It would be good to replace it with a bit higher quality image.

<img width="983" alt="Image 2020-12-30 at 8 23 36 am" src="https://user-images.githubusercontent.com/5704285/103336417-6a025200-4a78-11eb-8284-869a436ad56c.png">

**Comment by Danibelle** [comment]
I don't have a better image sadly

**Comment by Danibelle** [comment]
What can we do here, it still needs to be something different.
@markoprljic you said you don't want to mix photos with images in the intro - does that mean we can't reuse the photo graphic from the intro on this screen again? It's better than this one currently in there I Think!

![image](https://user-images.githubusercontent.com/39466970/105738691-27535e80-5eec-11eb-8020-b8e20ef538f8.png)

**Comment by markoprljic** [comment]
@Danibelle I thought we agreed to use the one in this comment https://github.com/commons-stack/c-sim-front-end/issues/65#issuecomment-752358022

**Comment by Danibelle** [comment]
Yes I"m in agreement!  It is still showing the old one right now, and this issue is scheduled for the public release, which I technically already gave thumbs up on ;) 

So I want to clarify the change for ..  @mendesfabio ?

**Comment by mendesfabio** [comment]
Image changed in #135. If you have more suggestions, @Danibelle, bring us new issues!
