### ISSUE TITLE
Missing a transition page to explain what HATCHERS are

### ISSUE THREAD

**Issue by Danibelle** [commons-stack/c-sim-front-end#66]
There needs to be a bit more information in Designing the Commons around How Many Hatchers, that explains what a Hatcher is and that you must choose how many.

Here is the text that is missing for continuity:

**Who can initiate a Commons? Trusted experts who accept accountability for upholding the values and honorable intentions of the community should be chosen to be the founding members of the RxC Commons.  These people are known as the ‘Hatchers’.**

Perhaps the image of the people that changes with the slider can be a little smaller, and this text inserted above the Question, How many Hatchers?

![image](https://user-images.githubusercontent.com/39466970/103251536-e9373f00-492d-11eb-8c6f-f08601f791ad.png)

**Comment by mendesfabio** [comment]
I started working on this. Since this page is dedicated to explaining what hatchers are, I think we could add more details.

![image](https://user-images.githubusercontent.com/43360747/103722442-b684ea80-4fae-11eb-9418-86cb21cb2882.png)

**Comment by Danibelle** [comment]
Yes, this looks great!
