### ISSUE TITLE
Weird '60' and 'days' in the selector tool on Voting Speed

### ISSUE THREAD

**Issue by Danibelle** [commons-stack/c-sim-front-end#69]
Selectable radio buttons are 3 days, 10 days, 30 days, 60 days..  then there's another 60, with the word days, trailing..

![image](https://user-images.githubusercontent.com/39466970/103252874-7a5ce480-4933-11eb-98aa-249e2cb0a844.png)

**Comment by MerlinEgalite** [comment]
hmm in fact, you can click on the second "60" to set the number of days of your choice like 27 days. but maybe the UI is not clear. Do you suggest to do it another way @Danibelle

**Comment by mendesfabio** [comment]
I think the last field should always show its placeholder, `Custom value`,  instead of reflecting the number of days selected on the inputs. But, when the user inputs some value there, the plot has to be updated and all inputs must be unchecked.

**Comment by MerlinEgalite** [comment]
<img width="1440" alt="Screenshot 2021-01-03 at 15 44 43" src="https://user-images.githubusercontent.com/44097430/103481354-c2b84e80-4dda-11eb-8bf9-aa08c7732716.png">
<img width="1440" alt="Screenshot 2021-01-03 at 15 44 33" src="https://user-images.githubusercontent.com/44097430/103481357-c3e97b80-4dda-11eb-9d18-644aad2d6960.png">

What about that? It's maybe easier for the user to understand he can enter a custom value?
Open to any comment!
