### ISSUE TITLE
Integrate RadX more into the content 

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/c-sim-front-end#7]
It should always be "RadX Commons" Not just Commons ... There might be more here...

<img width="363" alt="Screen Shot 2020-12-01 at 11 58 47 AM" src="https://user-images.githubusercontent.com/14945613/100771599-e284dd00-33fe-11eb-873e-60fae721668b.png">

<img width="376" alt="Screen Shot 2020-12-01 at 11 58 34 AM" src="https://user-images.githubusercontent.com/14945613/100771605-e44ea080-33fe-11eb-9656-bd1446fe1a63.png">

<img width="423" alt="Screen Shot 2020-12-01 at 11 58 14 AM" src="https://user-images.githubusercontent.com/14945613/100771607-e4e73700-33fe-11eb-92c1-ba9e1963c58d.png">

**Comment by Danibelle** [comment]
In accordance with branding:
RadicalxChange
or shorten to RxC
