### ISSUE TITLE
Good Future Bad Future share score links are incomplete

### ISSUE THREAD

**Issue by Danibelle** [commons-stack/c-sim-front-end#70]
Three fb links at bottom .. make two of them Twitter, LinkedIn, and .. copy link to share where ever?

![image](https://user-images.githubusercontent.com/39466970/103254685-2a821b80-493b-11eb-8f50-7f5bf0575b33.png)

**Comment by Danibelle** [comment]
PS I love this Good Future image.

**Comment by mendesfabio** [comment]
I've changed the icons. Now we need the content/text that will be shared on social media to implement this feature.

**Comment by Danibelle** [comment]
Something like: 

"I'm helping design a regenerative future for humanity on the Commons Simulator! Can you beat my high score at [link]?"
