### ISSUE TITLE
Remove EXIT link on Results page

### ISSUE THREAD

**Issue by markoprljic** [commons-stack/c-sim-front-end#74]
On the results page there is Exit link top right corner that should be removed. 
User has the option to exit game and try again with the buttons below the graphs. 

![Image 2020-12-30 at 8.25.54 am.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/38d56c4b-6665-4683-8732-3eaa91cdd6f4)

**Comment by mendesfabio** [comment]
There was also a Restart link on the left, so I took the liberty to remove that too.

**Comment by markoprljic** [comment]
Great!
