### ISSUE TITLE
Intro 5 - text edit from 'held' to 'holed'

### ISSUE THREAD

**Issue by Danibelle** [commons-stack/c-sim-front-end#9]
Intro 5 - basement gamers HOLED up

![image](https://user-images.githubusercontent.com/39466970/100805728-d5fb8700-33f4-11eb-8178-539fcd92afea.png)

**Comment by GriffGreen** [comment]
Wow!!! I did not know this is how that phrase was spelled :-D Thx Dani, GREAT CATCH!
