### ISSUE TITLE
Remove RadicalxChange from the title

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/c-sim-front-end#91]
The Commons Simulator will have multiple levels... we should call it "The Commons Simulator" and remove the RxC parts from the first page... 

![Screen Shot 2021-01-05 at 7.55.20 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/8d3e809f-08a3-4cb7-8b83-43dd0c59e992)

**Comment by mendesfabio** [comment]
> remove the RxC parts from the first page

You mean the RxC part (subtitle) on the page you attached, or on the following pages?

**Comment by GriffGreen** [comment]
for now... just call it "The Commons Simulator" and remove the word RadicalxChange

The RxC piece is a discussion for later (#92)
