### ISSUE TITLE
Fix output graphs' x axis

### ISSUE THREAD

**Issue by marthendalnunes** [commons-stack/c-sim-front-end#98]
The output graphs' x-axis is showing nonrounded days values. It could be changed to show rounded values such as 100, 150, 200 days, etc. The final value showed on the x-axis is different between graphs.
![image](https://user-images.githubusercontent.com/18421017/103779298-5031b380-5012-11eb-8966-a902fc40e737.png)

**Comment by MerlinEgalite** [comment]
If we show only the multiples of 25, is it okay?

**Comment by MerlinEgalite** [comment]
<img width="1440" alt="Screenshot 2020-12-24 at 08 55 49" src="https://user-images.githubusercontent.com/44097430/104019485-e81ed100-51bb-11eb-8b83-2f1b1dbf9af3.png">

**Comment by MerlinEgalite** [comment]
<img width="1080" alt="Screenshot 2021-01-08 at 14 14 34" src="https://user-images.githubusercontent.com/44097430/104019711-56fc2a00-51bc-11eb-8f48-465c03c4b681.png">

**Comment by marthendalnunes** [comment]
@MerlinEgalite seems interesting, but could you try to run this graph with this interval using 1095 timesteps? I feel that using 25 days of interval will still make the graph polluted. If you could try with 50 and 100 days to and send the image in here, all of them using 1095 timesteps, would be awesome.

**Comment by MerlinEgalite** [comment]
<img width="1440" alt="Screenshot 2021-01-08 at 20 20 08" src="https://user-images.githubusercontent.com/44097430/104055362-efab9d80-51ee-11eb-8cfe-c42e110f5b2f.png">
![Uploading Screenshot 2021-01-08 at 20.19.37.png…]()
sure!

**Comment by MerlinEgalite** [comment]
![Uploading Screenshot 2021-01-08 at 20.19.37.png…]()

**Comment by MerlinEgalite** [comment]
<img width="1440" alt="Screenshot 2021-01-08 at 20 19 37" src="https://user-images.githubusercontent.com/44097430/104055448-1d90e200-51ef-11eb-9ddd-4b0d674bf3c0.png">
